name: Build Package CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [centos7, ubuntu2204]

    steps:
    - uses: actions/checkout@v2
    - name: Build package
      run: docker-compose build ${{ matrix.os }}
